name: gazprom_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  injectable: ^2.2.0
  get_it: ^7.6.0
  intl: ^0.18.1
  geolocator: ^9.0.2
  json_annotation: ^4.8.1
  dio: ^5.3.2
  retrofit: ^4.0.1
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
     - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
  image_path: "assets/logo.png"
  min_sdk_android: 21
